//! The in-memory model of a notcron-managed unit.
//!
//! Everything the builder can edit lives here. Directives the model does not
//! understand survive in a free-text `manual` block that is rendered verbatim
//! at the end of the file, which is what makes a parse -> render round trip
//! lossless.

use super::escape;

/// Marker comment written into every generated file. Its presence is the
/// definition of "notcron owns this unit".
pub const MARKER: &str = "# Generated by notcron";
/// Secondary machine-readable marker, in `[Unit]`.
pub const X_MARKER: &str = "X-NotCron=1";
pub const HOMEPAGE: &str = "https://github.com/suchattai-labs/notcron-rs";
/// Every timer/service pair notcron creates is named `notcron-<name>`.
pub const PREFIX: &str = "notcron-";
/// Header introducing the free-text manual block at the end of a file.
pub const MANUAL_HEADER: &str = "# --- notcron:manual (free-form directives, preserved verbatim)";

/// User units (the default) or system units.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Scope {
    #[default]
    User,
    System,
}

impl Scope {
    pub fn as_str(self) -> &'static str {
        match self {
            Scope::User => "user",
            Scope::System => "system",
        }
    }

    /// The systemctl/journalctl flag for this scope.
    pub fn flag(self) -> &'static str {
        match self {
            Scope::User => "--user",
            Scope::System => "--system",
        }
    }
}

/// When a timer fires.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Schedule {
    /// One or more `OnCalendar=` values, ORed by systemd.
    Calendar(Vec<String>),
    /// `OnBootSec=` plus `OnUnitActiveSec=`: a plain repeating interval.
    Every { every: String, boot: String },
    /// `OnBootSec=` only: one shot, some time after boot.
    Boot { boot: String },
}

impl Default for Schedule {
    fn default() -> Self {
        Schedule::Calendar(vec!["*-*-* 00:00:00".into()])
    }
}

impl Schedule {
    /// One-line human summary, used in list views.
    pub fn summary(&self) -> String {
        match self {
            Schedule::Calendar(v) => v.join(" | "),
            Schedule::Every { every, boot } => format!("every {every} (first at boot+{boot})"),
            Schedule::Boot { boot } => format!("at boot + {boot}"),
        }
    }

    /// The calendar specs, if this is a calendar schedule.
    pub fn calendars(&self) -> &[String] {
        match self {
            Schedule::Calendar(v) => v,
            _ => &[],
        }
    }
}

/// `Type=` of a service unit.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ServiceType {
    #[default]
    Simple,
    Exec,
    Oneshot,
    Forking,
    Notify,
}

impl ServiceType {
    pub const ALL: [ServiceType; 5] = [
        ServiceType::Simple,
        ServiceType::Exec,
        ServiceType::Oneshot,
        ServiceType::Forking,
        ServiceType::Notify,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            ServiceType::Simple => "simple",
            ServiceType::Exec => "exec",
            ServiceType::Oneshot => "oneshot",
            ServiceType::Forking => "forking",
            ServiceType::Notify => "notify",
        }
    }

    pub fn parse(s: &str) -> Option<ServiceType> {
        ServiceType::ALL.into_iter().find(|t| t.as_str() == s)
    }
}

/// `Restart=` of a service unit.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum RestartPolicy {
    #[default]
    No,
    OnFailure,
    OnAbnormal,
    Always,
}

impl RestartPolicy {
    pub const ALL: [RestartPolicy; 4] = [
        RestartPolicy::No,
        RestartPolicy::OnFailure,
        RestartPolicy::OnAbnormal,
        RestartPolicy::Always,
    ];

    pub fn as_str(self) -> &'static str {
        match self {
            RestartPolicy::No => "no",
            RestartPolicy::OnFailure => "on-failure",
            RestartPolicy::OnAbnormal => "on-abnormal",
            RestartPolicy::Always => "always",
        }
    }

    pub fn parse(s: &str) -> Option<RestartPolicy> {
        RestartPolicy::ALL.into_iter().find(|t| t.as_str() == s)
    }
}

/// The `[Service]` knobs shared by timer-driven and standalone services.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ServiceOpts {
    pub service_type: ServiceType,
    pub exec_start: String,
    pub exec_start_pre: Option<String>,
    pub exec_stop_post: Option<String>,
    pub restart: RestartPolicy,
    pub restart_sec: Option<String>,
    pub working_directory: Option<String>,
    pub run_as: Option<String>,
    pub environment: Vec<String>,
}

/// A timer plus the service it drives.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TimerJob {
    pub schedule: Schedule,
    /// Human-readable note about what the user asked for, kept as a comment.
    pub source: String,
    pub persistent: bool,
    pub randomized_delay: Option<String>,
    pub service: ServiceOpts,
    /// Free-form directives appended to the .service file.
    pub service_manual: String,
    /// Free-form directives appended to the .timer file.
    pub timer_manual: String,
}

impl Default for TimerJob {
    fn default() -> Self {
        TimerJob {
            schedule: Schedule::default(),
            source: String::new(),
            persistent: true,
            randomized_delay: None,
            service: ServiceOpts {
                service_type: ServiceType::Oneshot,
                ..ServiceOpts::default()
            },
            service_manual: String::new(),
            timer_manual: String::new(),
        }
    }
}

/// A standalone (long-running or one-shot) service unit.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StandaloneService {
    pub service: ServiceOpts,
    pub wanted_by: String,
    pub manual: String,
}

impl Default for StandaloneService {
    fn default() -> Self {
        StandaloneService {
            service: ServiceOpts::default(),
            wanted_by: "multi-user.target".into(),
            manual: String::new(),
        }
    }
}

/// Preset filesystem flavours, each with sane default mount options.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum MountPreset {
    #[default]
    Block,
    Nfs,
    Cifs,
    Bind,
}

impl MountPreset {
    pub const ALL: [MountPreset; 4] = [
        MountPreset::Block,
        MountPreset::Nfs,
        MountPreset::Cifs,
        MountPreset::Bind,
    ];

    pub fn label(self) -> &'static str {
        match self {
            MountPreset::Block => "block device / local filesystem",
            MountPreset::Nfs => "NFS export",
            MountPreset::Cifs => "SMB/CIFS share",
            MountPreset::Bind => "bind mount",
        }
    }

    /// `Type=` for the preset. `auto` lets the kernel probe a block device.
    pub fn fstype(self) -> &'static str {
        match self {
            MountPreset::Block => "auto",
            MountPreset::Nfs => "nfs",
            MountPreset::Cifs => "cifs",
            MountPreset::Bind => "none",
        }
    }

    /// `Options=` defaults that are reasonable for each flavour.
    pub fn options(self) -> &'static str {
        match self {
            MountPreset::Block => "defaults,nofail",
            MountPreset::Nfs => "rw,soft,timeo=100,noatime,_netdev",
            MountPreset::Cifs => "rw,noatime,_netdev,credentials=/etc/cifs-credentials,uid=0,gid=0",
            MountPreset::Bind => "bind",
        }
    }

    /// Placeholder shown for `What=` so the field is self-documenting.
    pub fn what_hint(self) -> &'static str {
        match self {
            MountPreset::Block => "/dev/disk/by-uuid/...",
            MountPreset::Nfs => "server:/export/path",
            MountPreset::Cifs => "//server/share",
            MountPreset::Bind => "/source/directory",
        }
    }
}

/// A `.mount` unit, optionally paired with an `.automount`.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct MountUnit {
    pub preset: MountPreset,
    pub what: String,
    /// The mount point. The unit filename is derived from this.
    pub where_: String,
    pub fstype: String,
    pub options: String,
    pub automount: bool,
    pub timeout_idle: Option<String>,
    pub manual: String,
    pub automount_manual: String,
}

/// What kind of thing a unit is.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Body {
    Timer(Box<TimerJob>),
    Service(Box<StandaloneService>),
    Mount(Box<MountUnit>),
}

impl Body {
    pub fn kind_label(&self) -> &'static str {
        match self {
            Body::Timer(_) => "timer",
            Body::Service(_) => "service",
            Body::Mount(m) => {
                if m.automount {
                    "automount"
                } else {
                    "mount"
                }
            }
        }
    }
}

/// A complete notcron-managed unit (one or two files on disk).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Unit {
    /// Short name, without the `notcron-` prefix. Ignored for mounts, whose
    /// name is dictated by the mount point.
    pub name: String,
    pub description: String,
    pub scope: Scope,
    pub body: Body,
}

impl Unit {
    /// A new timer job with notcron's defaults.
    pub fn new_timer(scope: Scope) -> Unit {
        Unit {
            name: String::new(),
            description: String::new(),
            scope,
            body: Body::Timer(Box::default()),
        }
    }

    pub fn new_service(scope: Scope) -> Unit {
        Unit {
            name: String::new(),
            description: String::new(),
            scope,
            body: Body::Service(Box::default()),
        }
    }

    /// Mount units are system-only by nature: the kernel mount namespace is
    /// not something a user manager can act on.
    pub fn new_mount() -> Unit {
        let mut m = MountUnit {
            preset: MountPreset::Block,
            ..MountUnit::default()
        };
        m.fstype = MountPreset::Block.fstype().into();
        m.options = MountPreset::Block.options().into();
        Unit {
            name: String::new(),
            description: String::new(),
            scope: Scope::System,
            body: Body::Mount(Box::new(m)),
        }
    }

    /// The unit name stem: `notcron-backup`, or the escaped mount point.
    pub fn stem(&self) -> Result<String, String> {
        match &self.body {
            Body::Mount(m) => escape::escape_path(&m.where_),
            _ => Ok(prefixed(&self.name)),
        }
    }

    /// Every file this unit occupies, e.g. `["x.timer", "x.service"]`. The
    /// primary (enable/start target) file is first.
    pub fn filenames(&self) -> Result<Vec<String>, String> {
        let stem = self.stem()?;
        Ok(match &self.body {
            Body::Timer(_) => vec![format!("{stem}.timer"), format!("{stem}.service")],
            Body::Service(_) => vec![format!("{stem}.service")],
            Body::Mount(m) => {
                if m.automount {
                    vec![format!("{stem}.automount"), format!("{stem}.mount")]
                } else {
                    vec![format!("{stem}.mount")]
                }
            }
        })
    }

    /// The unit systemctl acts on for enable/disable/start/stop.
    pub fn primary_unit(&self) -> Result<String, String> {
        Ok(self.filenames()?.remove(0))
    }

    /// The unit whose journal is interesting (the service, not the timer).
    pub fn log_unit(&self) -> Result<String, String> {
        let stem = self.stem()?;
        Ok(match &self.body {
            Body::Timer(_) | Body::Service(_) => format!("{stem}.service"),
            Body::Mount(_) => format!("{stem}.mount"),
        })
    }

    /// Validate everything the renderer relies on. Returns a human-readable
    /// message for the first problem found.
    pub fn validate(&self) -> Result<(), String> {
        match &self.body {
            Body::Mount(m) => {
                if m.where_.trim().is_empty() {
                    return Err("mount point (Where=) must not be empty".into());
                }
                escape::escape_path(&m.where_)?;
                if m.what.trim().is_empty() {
                    return Err("mount source (What=) must not be empty".into());
                }
                if m.fstype.trim().is_empty() {
                    return Err("filesystem type (Type=) must not be empty".into());
                }
            }
            _ => {
                validate_name(&self.name)?;
                let svc = match &self.body {
                    Body::Timer(t) => &t.service,
                    Body::Service(s) => &s.service,
                    Body::Mount(_) => unreachable!(),
                };
                if svc.exec_start.trim().is_empty() {
                    return Err("ExecStart= must not be empty".into());
                }
                for e in &svc.environment {
                    if !e.contains('=') {
                        return Err(format!("environment entry '{e}' is not KEY=VALUE"));
                    }
                }
            }
        }
        if self.description.contains('\n') {
            return Err("description must be a single line".into());
        }
        Ok(())
    }
}

/// Add the `notcron-` prefix, but only once.
pub fn prefixed(name: &str) -> String {
    if name.starts_with(PREFIX) {
        name.to_string()
    } else {
        format!("{PREFIX}{name}")
    }
}

/// Strip the `notcron-` prefix if present.
pub fn unprefixed(name: &str) -> &str {
    name.strip_prefix(PREFIX).unwrap_or(name)
}

pub fn validate_name(name: &str) -> Result<(), String> {
    if name.is_empty() {
        return Err("unit name must not be empty".into());
    }
    if !name
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-'))
    {
        return Err(format!(
            "unit name '{name}' contains invalid characters (use A-Z a-z 0-9 . _ -)"
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn prefix_is_applied_once() {
        assert_eq!(prefixed("backup"), "notcron-backup");
        assert_eq!(prefixed("notcron-backup"), "notcron-backup");
        assert_eq!(unprefixed("notcron-backup"), "backup");
        assert_eq!(unprefixed("backup"), "backup");
    }

    #[test]
    fn timer_occupies_two_files_with_the_timer_first() {
        let mut u = Unit::new_timer(Scope::User);
        u.name = "backup".into();
        assert_eq!(
            u.filenames().unwrap(),
            ["notcron-backup.timer", "notcron-backup.service"]
        );
        assert_eq!(u.primary_unit().unwrap(), "notcron-backup.timer");
        assert_eq!(u.log_unit().unwrap(), "notcron-backup.service");
    }

    #[test]
    fn mount_filenames_come_from_the_mount_point() {
        let mut u = Unit::new_mount();
        if let Body::Mount(m) = &mut u.body {
            m.where_ = "/srv/my-share".into();
            m.automount = true;
        }
        assert_eq!(
            u.filenames().unwrap(),
            ["srv-my\\x2dshare.automount", "srv-my\\x2dshare.mount"]
        );
    }

    #[test]
    fn validation_catches_the_obvious_mistakes() {
        let mut u = Unit::new_timer(Scope::User);
        assert!(u.validate().is_err()); // no name
        u.name = "bad name".into();
        assert!(u.validate().is_err()); // space in name
        u.name = "backup".into();
        assert!(u.validate().is_err()); // no ExecStart
        if let Body::Timer(t) = &mut u.body {
            t.service.exec_start = "/bin/true".into();
        }
        assert!(u.validate().is_ok());
        if let Body::Timer(t) = &mut u.body {
            t.service.environment.push("NOPE".into());
        }
        assert!(u.validate().is_err());
    }

    #[test]
    fn mount_validation_requires_an_absolute_mount_point() {
        let mut u = Unit::new_mount();
        if let Body::Mount(m) = &mut u.body {
            m.what = "/dev/sdb1".into();
            m.where_ = "relative".into();
        }
        assert!(u.validate().is_err());
        if let Body::Mount(m) = &mut u.body {
            m.where_ = "/mnt/data".into();
        }
        assert!(u.validate().is_ok());
    }
}
